[toolchain]
anchor_version = "0.31.1"

[programs.localnet]
basalt_cdp_mvp = "5gzoSxVDDSjdE3pPYu9GuyaDAyV2uBXm34BvWa5epsv3"

[programs.devnet]
basalt_cdp_mvp = "5gzoSxVDDSjdE3pPYu9GuyaDAyV2uBXm34BvWa5epsv3"

[programs.testnet]
basalt_cdp_mvp = "5gzoSxVDDSjdE3pPYu9GuyaDAyV2uBXm34BvWa5epsv3"

[programs.mainnet]
basalt_cdp_mvp = "5gzoSxVDDSjdE3pPYu9GuyaDAyV2uBXm34BvWa5epsv3"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/user2/.config/solana/basalt.json"

[scripts]
test = "npx ts-mocha -p ./tests/tsconfig.json -t 1000000 tests/**/*.ts"