// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/docs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/docs";
  };
  "./solana/SolanaProvider.tsx": {
    id: "solana/SolanaProvider";
    page: "/" | "/docs";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/docs.tsx": {
    id: "routes/docs";
    page: "/docs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "solana/SolanaProvider": typeof import("./app/./solana/SolanaProvider.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/docs": typeof import("./app/routes/docs.tsx");
};